import { motion } from "framer-motion";

export default function InterruptExplorer({ interruptData, selectedSection, onSelectSection }) {
  const section =
    interruptData.sections.find((item) => item.id === selectedSection) || interruptData.sections[0];

  return (
    <>
      <section className="detail-card">
        <div className="interrupt-tabs">
          {interruptData.sections.map((item) => (
            <button
              key={item.id}
              type="button"
              className={`subtab ${item.id === section.id ? "active" : ""}`}
              onClick={() => onSelectSection(item.id)}
            >
              {item.title}
            </button>
          ))}
        </div>

        <h2>{section.title}</h2>
        <p>{section.summary}</p>

        <div className={`flow-demo ${section.id}`}>
          {section.steps.map((step, index) => (
            <div className="flow-row" key={step}>
              <motion.div
                className="flow-step"
                initial={{ opacity: 0.35, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: index * 0.08 }}
              >
                <span>{step}</span>
              </motion.div>
              {index < section.steps.length - 1 ? <div className="flow-arrow" /> : null}
            </div>
          ))}
        </div>

        <div className="note-grid">
          {section.examples.map((example) => (
            <div className="note-card" key={example}>{example}</div>
          ))}
        </div>
      </section>

      <section className="detail-grid">
        <section className="detail-card">
          <h3>External Interrupt Modes</h3>
          <table className="data-table">
            <thead>
              <tr>
                <th>EICRA bits</th>
                <th>Meaning</th>
              </tr>
            </thead>
            <tbody>
              {interruptData.modeTable.map((row) => (
                <tr key={row.bits}>
                  <td>{row.bits}</td>
                  <td>{row.meaning}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </section>

        <section className="detail-card">
          <h3>Timer Overview</h3>
          {interruptData.timerOverview.map((timer) => (
            <div className="timer-overview-card" key={timer.name}>
              <h4>
                {timer.name} <span>{timer.width}</span>
              </h4>
              <p>{timer.highlights.join(" ")}</p>
              <div className="chip-wrap">
                {timer.registers.map((item) => (
                  <span className="chip" key={item}>{item}</span>
                ))}
              </div>
            </div>
          ))}
        </section>

        <section className="detail-card">
          <h3>Conceptual Differences</h3>
          <div className="compare-list">
            <div><strong>External interrupt:</strong> dedicated line, precise mode selection, best for D2 and D3 edge detection.</div>
            <div><strong>Pin-change interrupt:</strong> many pins share one group ISR, software must identify the changed bit.</div>
            <div><strong>Timer interrupt:</strong> generated by hardware counting, independent of pin edges.</div>
            <div><strong>Polling in loop():</strong> simple and visible, but software checks later and can miss short events.</div>
          </div>
        </section>
      </section>
    </>
  );
}
